### ISSUE TITLE
In mac whenwe hover over the images on the homepage then the hand coursor is not coming in mac system.

### ISSUE THREAD

**Issue by sudhanshu0603** [stores-cedcommerce/Cathleen-Thomas#1]
**Actual result:**
In mac whenwe hover over the images on the homepage then the hand coursor is not coming in mac system.
![image](https://user-images.githubusercontent.com/102131636/168747578-13837432-222c-4c13-a19f-bd9405b71bce.png)

**The video issue:**
https://www.awesomescreenshot.com/video/8939846?key=eb495f172694b4312ad6b826c0e5f585

**Expected result:**
The hand cursor have to come when we hover over the images on the home page.
![image](https://user-images.githubusercontent.com/102131636/168747525-ed32f37e-5171-4b3e-9ee2-75c8eb81a39d.png)

**Comment by devabulabbas** [comment]
Done

**Comment by sudhanshu0603** [comment]
ok, resolved
